### ISSUE TITLE
How to enroll finger print for each user?

### ISSUE THREAD

**Issue by aice09** [kamshory/ZKLibrary#33]
How to enroll finger print for each user? 
I try `getUserTemplate` function but nothing display or no data output!

**Comment by Tehsseen** [comment]
Same issue someone help please

**Comment by kamshory** [comment]
Enroll fingerprint with PHP is not recommended. This library ONLY for read time attendance and integrate it to your application.

**Comment by FairouzGattoufi** [comment]
@kamshory can you suggest us, what we can do to get fingerprint data  if in this library there is no solution to get it. Then anyother idea to get it ???
