### ISSUE TITLE
I can not add user by use setUser()

### ISSUE THREAD

**Issue by maodahua** [kamshory/ZKLibrary#52]
$kaoqin->setUser('555555', '555555', 'm', '123456', LEVEL_USER);
I use this but I can not add a user to machine. 
the device is F18 .could you help me ? please

**Comment by kamshory** [comment]
Please remember that $uid is 2 bytes number (1 to 65535). But the maximum number is depend on your device. For example, your device only can save 1000 user, so you probably can not use $uid more than 1000.
